swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts:      
    get:
      security:
        - Bearer: []
      tags:
        - User Account Module
      summary: Get an Account
      description: API for get an account
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '201':
          description: Get account successfully
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
  /user/profile/accounts/transactions/{transactionId}/category:
    patch:
      security:
        - Bearer: []
      tags:
        - User Account Module
      summary: Update Transaction Category
      description: API to update the category of a transaction.
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update.
          required: true
          type: string
        - in: body
          name: body
          description: New category for the transaction.
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                enum:
                  - Option 1
                  - Option 2
                  - Option 3
      responses:
        '200':
          description: Category updated successfully.
          schema:
            $ref: '#/definitions/TransactionResponse'
        '404':
          description: Unknown Category
        '500':
          description: Internal Server Error
  /user/profile/accounts/transactions/{transactionId}/note:
    patch:
      security:
        - Bearer: []
      tags:
        - User Account Module
      summary: Add or update Note to Transaction
      description: API to add or update a note to a transaction.
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to add or update a note to.
          required: true
          type: string
        - in: body
          name: body
          description: Request body to add a note.
          required: true
          schema: 
            type: object
            properties:
              note:
                type: string
      responses:
        '201':
          description: Note added successfully.
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          account:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                accountNumber:
                  type: string
                balance:
                  type: number
                transactions:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      accountId:
                        type: string
                      date:
                        type: string
                      description:
                        type: string
                      amount:
                        type: number
                      type:
                        type: string
                      category:
                        type: string
                      note:
                        type: string

  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          type:
            type: string
          category:
            type: string
          note:
            type: string
